# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

stages:
 - stage: Build
   jobs:
   - job: Build

  pool:
    vmImage: 'windows-latest'

  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'
      vsVersion: '16.0'